### PR TITLE
fix: newlines in enum members and add XElement support.

### LINKED ISSUE #23: NewLines in <summary> of Enum Members
For Enums a markdown table is generated. If an enum member's summary contains new lines the markdown table breaks.
c#
```c#
public enum MyEnum
{
    /// <summary>
    /// This
    /// is
    /// a
    /// long
    /// summary.
    /// </summary>
    Value1
```

markdown
```md
## Fields

| Name | Value | Description |
| --- | --: | --- |
| Value1 | 0 | this
            is
            a
            long
            summary. |

```

### PR DESCRIPTION
**Pull request by TimothyMakkison**
Resolves #23 

- Remove newlines from enum summaries so the generated markdown table doesn't break
- Add proper XElement to markdown support for Enums

## Example
```C#
// ...
/// <summary>
/// The default value for <see cref="MyEnum"/>.
/// This is additional information.
/// </summary>
Default = 0,
```

### Before

| Name | Value | Description |
| --- | --: | --- |
| Default | 0 | The default value for .
            This is additional information. |
| First | 1 | The first. |
| Second | 2 | The second. |

### After
| Name | Value | Description |
| --- | --: | --- |
| Default | 0 | The default value for [MyEnum](./myclasslib.myenum). This is additional information. |
| First | 1 | The first. |
| Second | 2 | The second. |

### CODE REVIEW

**Comment by TimothyMakkison** [comment]
Hey,@charlesdevandiere have you had a chance to look at this PR?

File: src/XMLDoc2Markdown/TypeDocumentation.cs [hunk 1]
```diff
@@ -454,14 +455,38 @@ private void WriteEnumFields(IEnumerable<FieldInfo> fields)
...
-                string paramDoc = this.documentation.GetMember(field)?.Element("summary")?.Value ?? String.Empty;
-                table.AddRow(new MarkdownTableRow(field.Name, ((Enum)Enum.Parse(this.type, field.Name)).ToString("D"), paramDoc.Trim()));
+                IEnumerable<XNode> nodes = this.documentation.GetMember(field)?.Element("summary")?.Nodes();
+                if (nodes == null)
+                {
+                    continue;
+                }
+
+                MarkdownParagraph summary = this.XNodesToMarkdownParagraph(nodes);
+                string formattedSummary = TableFormat(summary.ToString());
```
Comment (charlesdevandiere) [inline src/XMLDoc2Markdown/TypeDocumentation.cs:465]: I think this should work:
```csharp
string formattedSummary = summary.Replace("\r\n", string.Empty).Replace('\n', string.Empty);
```

**Review by charlesdevandiere — COMMENTED** [review]
Thank you very much for your pull request and sorry for my late reply

File: src/XMLDoc2Markdown/TypeDocumentation.cs (hunk 1 above)
Comment (TimothyMakkison) [reply src/XMLDoc2Markdown/TypeDocumentation.cs:465]: I used IsNullOrWhiteSpace to remove any strings that are just padding. 

```C#
/// <summary>
/// The default value for <see cref="MyEnum"/>.
/// Hello world
///     Hey              
///     Spaces
///      
///  
///  
///     
///     
/// Space 
/// 
///     <see cref="MyEnum"/>
/// This is additional information.
/// </summary>
```

Using `TableFormat`:
| Default | 0 | The default value for [MyEnum](./myclasslib.myenum). Hello world Hey  Spaces Space  [MyEnum](./myclasslib.myenum) This is additional information. |

With string replace:
| Default | 0 | The default value for [MyEnum](./myclasslib.myenum). Hello world Hey  Spaces      Space   [MyEnum](./myclasslib.myenum) This is additional information. |

You can't see the difference due to markdown 😄 but the string replace version will create several whitespace characters if several newlines/spaces are used.

Comment (charlesdevandiere) [reply src/XMLDoc2Markdown/TypeDocumentation.cs:465]: You're right. I merge. Thank you very much for your contribution!
